name: CI/CD - Build and Push BistroFlow

on:
  push:
    branches:
      - 'main'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t adeelhussain12/bistro-flow:latest -f ./backend/Dockerfile .

      - name: Push Docker image
        run: docker push adeelhussain12/bistro-flow:latest
